### ISSUE TITLE
Better output when submitting request

### ISSUE THREAD

**Issue by PhantHive** [Phearion/big-brain#7]
**Is your feature request related to a problem? Please describe.**
With the new modification on  big brain repo for handling data from sushi, the pdfs  are shown in row instead of column.

**Describe the solution you'd like**
A better output, pdfs in column and a small message  to tell the user about the output.
In addition, we should also, disable the button and input field when result is pending. 
And we should automatically reset input to empty string when submit clicked.

**Additional context**
![Capture d'écran 2023-12-06 184648](https://github.com/ipsa-scrypt/big-brain/assets/49699418/3f994ac0-53cf-402e-8223-21ed57ccc9bb)

**Comment by PhantHive** [comment]
Tell  me when you need me to open up the gradio space so that SUSHI works 😆 It cost a lot per minute so it's sleeping at the moment :'(

**Comment by PyyLog** [comment]
I understand ! We can talk about gradio space activation tomorrow. I don't plan to work on the issue tonight.

**Comment by PhantHive** [comment]
Resolved and merged I guess 😎
